import { Component, componentRegistry, $, esc } from '../components.js';

/**
 * Overview 组件 — generates the full overview DOM (hero, strip, grid).
 * After initial render, data refresh is handled by main.js imperative updates.
 */
class Overview extends Component {
    constructor(selector) {
        super(selector);
        this.children = [];
    }

    template() {
        return `
            <!-- Header -->
            <div class="overview-header">
                <h1 id="hero-status">路由正常</h1>
                <div class="overview-subtitle">
                    <span class="pulse-dot"></span>
                    <span id="hero-health-text">代理运行中</span>
                </div>
            </div>

            <!-- Stats Grid — 4 cards -->
            <div class="stats-grid">
                <div class="stat-card">
                    <span class="stat-label">服务状态</span>
                    <span class="stat-value" id="health-value">OK</span>
                    <span class="stat-note">/health 端点</span>
                </div>
                <div class="stat-card">
                    <span class="stat-label">总请求</span>
                    <span class="stat-value" id="total-value">0</span>
                    <span class="stat-note" id="total-note">当前进程</span>
                </div>
                <div class="stat-card">
                    <span class="stat-label">文本路由</span>
                    <span class="stat-value" id="text-value">0</span>
                    <span class="stat-note" id="text-share">0% 请求</span>
                </div>
                <div class="stat-card">
                    <span class="stat-label">错误</span>
                    <span class="stat-value" id="error-value">0</span>
                    <span class="stat-note" id="error-share">0% 错误率</span>
                </div>
            </div>

            <!-- Main Content: 2 columns -->
            <div class="overview-grid">
                <!-- Left: Recent Requests -->
                <div class="panel">
                    <div class="panel-head">
                        <h2>最近请求</h2>
                        <div class="filters">
                            <button class="active" onclick="filterLogs('all', this)">全部</button>
                            <button onclick="filterLogs('text', this)">文本</button>
                            <button onclick="filterLogs('multimodal', this)">图片</button>
                            <button onclick="filterLogs('error', this)">错误</button>
                        </div>
                    </div>
                    <table>
                        <thead>
                            <tr>
                                <th>时间</th>
                                <th>类型</th>
                                <th>来源模型</th>
                                <th>路由后端</th>
                                <th>状态</th>
                            </tr>
                        </thead>
                        <tbody id="recent-body">
                            <tr><td colspan="5">暂无记录</td></tr>
                        </tbody>
                    </table>
                </div>

                <!-- Right: Backend Status -->
                <div class="overview-right">
                    <div class="panel">
                        <div class="panel-head">
                            <h2>后端状态</h2>
                            <span>当前生效</span>
                        </div>
                        <div class="panel-body">
                            <div class="backend-list">
                                <div class="backend-item" id="text-backend"></div>
                                <div class="backend-item" id="image-backend"></div>
                            </div>
                        </div>
                    </div>
                    <div class="panel">
                        <div class="panel-head">
                            <h2>配置热重载</h2>
                            <span>无需重启</span>
                        </div>
                        <div class="panel-body">
                            <div class="reload-card">
                                <div class="reload-time" id="reload-big">--</div>
                                <div class="reload-status" id="reload-copy">等待读取配置</div>
                            </div>
                            <div class="config-keys" id="key-list"></div>
                        </div>
                    </div>
                    <div class="panel">
                        <div class="panel-head">
                            <h2>API 端点</h2>
                        </div>
                        <div class="panel-body list" id="api-mini"></div>
                    </div>
                </div>
            </div>
        `;
    }

    bindEvents() {
        // Filter buttons events are handled globally
    }

    afterRender() {
        // Overview HTML (hero, strip, grid) is generated by template().
        // Data refresh is handled by main.js imperative updates — avoids
        // full re-render which would lose scroll/filter/editor state.
    }

    updateData(stats, textBackend, imageBackend, logs) {
        this.options = { ...this.options, stats, textBackend, imageBackend, logs };
    }
}

export { Overview };
componentRegistry.register('Overview', Overview);